/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

import org.junit.jupiter.api.Test;
import stack.queue.stack_queue.Queue;
import stack.queue.stack_queue.Stack;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
  @Test
  void stackTest() {

    Stack stack = new Stack();
    assertTrue(stack.isEmpty());
    assertEquals("empty", stack.pop());

    stack.push("sanaa");
    stack.push("good");


    assertEquals("good", stack.peek());
    assertFalse(stack.isEmpty());

    assertEquals("good",stack.pop());
    assertEquals("sanaa", stack.peek());

  }
  @Test
  void queueTest() {

    Queue queue = new Queue();
    assertTrue(queue.isEmpty());
    assertEquals("empty", queue.deQueue());

    queue.enQueue("sanaa");
    queue.enQueue("good");


    assertEquals("sanaa", queue.peek());
    assertFalse(queue.isEmpty());

    assertEquals("sanaa",queue.deQueue());
    assertEquals("good", queue.peek());


  }

}
