/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

      Graph myGraph = new Graph();
      myGraph.addNode("8");
      myGraph.addNode("3");
      myGraph.addNode("1");
      myGraph.addNode("9");
      myGraph.addNode("6");
      myGraph.addNode("5");


      myGraph.addEdge("8" , "3");
      myGraph.addEdge("8" , "9");
      myGraph.addEdge("8" , "1");
      myGraph.addEdge("6" , "5");
      System.out.println(myGraph);
      System.out.println(myGraph.getNodes());
      System.out.println(myGraph.getNeighbors("8"));
      System.out.println(myGraph.getNeighbors("7"));
      System.out.println(myGraph.getNeighbors("5"));
      System.out.println(myGraph.size());
    }
}
