/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge05;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import challenge05.structure.LinkedList;

class MainTest {
  //    @Test void appHasAGreeting() {
//        Main classUnderTest = new Main();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  @Test
  void testJoin() {
    LinkedList fun = new LinkedList();

    LinkedList linkedList1 = new LinkedList();
    linkedList1.insert("S");
    linkedList1.insert("A");
    linkedList1.insert("N");
    linkedList1.insert("A");
    linkedList1.insert("A");

    LinkedList linkedList2 = new LinkedList();

    linkedList2.insert("K");
    linkedList2.insert("D");
    linkedList2.insert("O");
    linkedList2.insert("B");
    linkedList2.insert("Z");
    fun.head = fun.merge(linkedList1, linkedList2);
    assertEquals("HEAD ->{S} -> {K} -> {A} -> {D} -> {N} -> {O} -> {A} -> {B} -> {A} -> {Z} -> NULL", fun.stringOutput());
  }


}
