/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
  void maxValueTest(){
      BinaryTree<String> newTree3 = new BinaryTree<>();
      newTree3.add(10);
      newTree3.add(20);
      newTree3.add(100);
      assertEquals(100,newTree3.findMaxValue());
    }
  @Test
  public void breadthFirstTester() {
    BinaryTree<Integer> newTree4 = new BinaryTree<>();
    newTree4.add(20);
    newTree4.add(5);
    newTree4.add(83);
    newTree4.add(22);
    newTree4.add(33);

      assertEquals("[20, 5, 83, 22, 33]", BinaryTree.breadthFirst(newTree4).toString());

  }
  @Test
  public void fizzBuzzTest(){
    kTree ktree = new kTree();
    NodeK root = new NodeK("4");
    NodeK node1 = new NodeK("15");
    NodeK node2 = new NodeK("20");
    NodeK node3 = new NodeK("65");

    ktree.root = root;
    root.children.add(node1);
    root.children.add(node2);
    node1.children.add(node3);
    assertEquals("4 FizzBuzz Buzz Buzz ",ktree.fizzBuzz(root));
  }
}
