/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
  void maxValueTest(){
      BinaryTree<String> newTree3 = new BinaryTree<>();
      newTree3.add(10);
      newTree3.add(20);
      newTree3.add(100);
      assertEquals(100,newTree3.findMaxValue());
    }
}
