/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
  void maxValueTest(){
      BinaryTree<String> newTree3 = new BinaryTree<>();
      newTree3.add(10);
      newTree3.add(20);
      newTree3.add(100);
      assertEquals(100,newTree3.findMaxValue());
    }
  @Test
  public void breadthFirstTester() {
    BinaryTree<Integer> newTree4 = new BinaryTree<>();
    newTree4.add(20);
    newTree4.add(5);
    newTree4.add(83);
    newTree4.add(22);
    newTree4.add(33);

      assertEquals("[20, 5, 83, 22, 33]", BinaryTree.breadthFirst(newTree4).toString());

  }
}
