/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch26;

import java.util.Arrays;

import static ch26.Sort.insertionSort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

      System.out.println(new App().getGreeting());

      int [] newArr={10,4,23,8,16,79};
     System.out.println(Arrays.toString(insertionSort(newArr)));
    }


}
