/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge05;


import challenge05.structure.LinkedList;

public class Main {

  public static void main(String[] args) {
    LinkedList list = new LinkedList();

    LinkedList linkedList = new LinkedList();

    linkedList.insert("S");
    linkedList.insert("A");
    linkedList.insert("N");
    linkedList.insert("C");
    linkedList.insert("Q");
    LinkedList linkedList2 = new LinkedList();


    linkedList2.insert("K");
    linkedList2.insert("D");
    linkedList2.insert("O");
    linkedList2.insert("B");
    linkedList2.insert("Z");


//    linkedList.append("O");
//    linkedList.insertBefore("N","L");
//    linkedList.insertAfter("N","W");
//
    linkedList.stringOutput();
    linkedList2.stringOutput();


//    linkedList.merge(linkedList,linkedList2);
    System.out.println(linkedList.stringOutput());

//    String sss=linkedList.kthFromEnd(0);
//    System.out.println(sss);

    System.out.println(linkedList2.stringOutput());
    list.head = list.merge(linkedList, linkedList2);
    System.out.println("List for Zip function ==> ");
    System.out.println(list.stringOutput());
    System.out.println("  " + linkedList.includes("A") + "  ");
  }
}

