/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge05;


import challenge05.structure.LinkedList;

public class Main {

  public static void main(String[] args) {

    LinkedList linkedList = new LinkedList();

    linkedList.insert("S");
    linkedList.insert("A");
    linkedList.insert("N");
    linkedList.insert("C");
    linkedList.insert("Q");


    linkedList.append("O");
    linkedList.insertBefore("N","L");
    linkedList.insertAfter("N","W");
    linkedList.stringOutput();
    String sss=linkedList.kthFromEnd(0);
    System.out.println(sss);
    System.out.println("  " + linkedList.includes("A") + "  ");
  }
}

