/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge05;


import challenge05.structure.LinkedList;

public class Main {

  public static void main(String[] args) {

    LinkedList linkedList = new LinkedList();

    linkedList.insert("S");
    linkedList.insert("A");
    linkedList.insert("N");
    linkedList.insert("A");
    linkedList.insert("A");

    linkedList.stringOutput();

    System.out.println("  " + linkedList.includes("A") + "  ");
  }
}

