/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import Graph.App;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
  @Test void addNodeTest(){

    Graph graph = new Graph();

    graph.addNode("10");
    assertEquals("[10]", graph.getNodes().toString());


  }
//  @Test void addedgeTest(){
//
//    Graph graph = new Graph();
//
//    graph.addNode("5");
//    graph.addNode("2");
//
//    graph.addEdge("5", "2");
//
//    assertEquals("[2, 5]",graph.getNodes().toString());
//    assertEquals(2, graph.size());
//  }
  @Test
  public void emptyGraph(){

    Graph graph = new Graph();
    assertEquals(0,graph.size());

  }
//  @Test
//  public void breadthFirstTest(){
//    Graph myGraph = new Graph();
//    myGraph.addNode("8");
//    myGraph.addNode("3");
//    myGraph.addNode("1");
//    myGraph.addNode("9");
//    myGraph.addNode("6");
//    myGraph.addNode("5");
//
//
//    myGraph.addEdge("8" , "3");
//    myGraph.addEdge("8" , "9");
//    myGraph.addEdge("8" , "1");
//    myGraph.addEdge("6" , "5");
//
//    assertEquals("[8, 3, 9, 1]",myGraph.breadthFirst("8").toString());
//
//  }


  @Test
  public void businessTripTest(){
    Graph myGraph = new Graph();
    myGraph.addNode("8");
    myGraph.addNode("1");
    myGraph.addNode("2");
    myGraph.addNode("9");
    myGraph.addNode("7");
    myGraph.addNode("5");



    myGraph.addEdge("8" , "1" , 50);
    myGraph.addEdge("5" , "1" , 70);
    myGraph.addEdge("7" , "5", 20);
    myGraph.addEdge("8" , "9", 100);
    myGraph.addEdge("8" , "2", 40);
//    String[] trip = {"8" , "1" , "5"};
//    String[] trip2 = {"8" , "5"};
    String[] trip3 = {"8" , "1" , "5" , "7" , "5" , "1" , "8" , "9"};


        assertEquals("true, $380",myGraph.businessTrip("8",trip3).toString());

  }

}
