/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import Graph.App;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
  @Test void addNodeTest(){

    Graph graph = new Graph();

    graph.addNode("10");
    assertEquals("[10]", graph.getNodes().toString());


  }
  @Test void addedgeTest(){

    Graph graph = new Graph();

    graph.addNode("5");
    graph.addNode("2");

    graph.addEdge("5", "2");

    assertEquals("[2, 5]",graph.getNodes().toString());
    assertEquals(2, graph.size());
  }
  @Test
  public void emptyGraph(){

    Graph graph = new Graph();
    assertEquals(0,graph.size());

  }

}
