/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

import stack.queue.stack_queue.Queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


      Queue osaidQueue = new Queue();
      osaidQueue.enQueue("Killing");
      osaidQueue.enQueue("In");
      osaidQueue.enQueue("The");
      osaidQueue.enQueue("Name");
      osaidQueue.enQueue("Of");

      System.out.println(osaidQueue.isEmpty());


    }
    }
}
