/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

//import stack.queue.stack_queue.Queue;
import stack.queue.stack_queue.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


      pseudoQueue newQueue = new pseudoQueue();
      newQueue.enQueue("S");
      newQueue.enQueue("A");
      newQueue.enQueue("N");
      newQueue.enQueue("A");
      newQueue.enQueue("A");


      System.out.println(newQueue.printData());
newQueue.deQueue();
      System.out.println(newQueue.printData());


      //================================================================

      Animal cat = new Cat("fshfhsy");
      Animal dog = new Dog("dogdog");
      AnimalShelter.enqueue(cat);
      AnimalShelter.enqueue(dog);
      System.out.println(AnimalShelter.getAnimalQueue().toString());
      System.out.println(AnimalShelter.dequeue().getName());
      System.out.println(AnimalShelter.dequeue().getName());

    }

}
