/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.queue;

//import stack.queue.stack_queue.Queue;
import stack.queue.stack_queue.StackQueueBrackets;
import stack.queue.stack_queue.pseudoQueue;
import stack.queue.stack_queue.Queue;
import stack.queue.stack_queue.Stack;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


      pseudoQueue newQueue = new pseudoQueue();
      newQueue.enQueue("S");
      newQueue.enQueue("A");
      newQueue.enQueue("N");
      newQueue.enQueue("A");
      newQueue.enQueue("A");


      System.out.println(newQueue.printData());
newQueue.deQueue();
      System.out.println(newQueue.printData());


      //========================================================================

StackQueueBrackets data2 =new StackQueueBrackets();

      System.out.println(data2.stackQueueBrackets("{(})"));


    

      StackQueueBrackets data2 =new StackQueueBrackets();

      System.out.println(data2.stackQueueBrackets("{(})"));

    }

}
