/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test void HashTableTest() {
    HashTable HashTest= new HashTable();

    HashTest.add("Naim", 1000);
    assertEquals(9, HashTest.hash("John"));

    assertEquals(null, HashTest.get("Qusai"));


    assertEquals(null , HashTest.get("null"));

    assertEquals(true , HashTest.contains("Jason"));
    assertEquals(false , HashTest.contains("abrar"));


  }
}
